<?php

use App\Counter;
use PHPUnit\Framework\TestCase;

class CounterTest extends TestCase
{
    private $counter;

    protected function setUp(): void
    {
        $this->counter = new Counter();
    }
    /** @test */
    public function countTest(): void
    {
        $this->assertEquals([
            1,
            2,
            "falabella",
            4,
            "IT",
            "falabella",
            7,
            8,
            "falabella",
            "IT",
            11,
            "falabella",
            13,
            14,
            "integraciones",
            16,
            17,
            "falabella",
            19,
            "IT",
            "falabella",
            22,
            23,
            "falabella",
            "IT",
            26,
            "falabella",
            28,
            29,
            "integraciones",
            31,
            32,
            "falabella",
            34,
            "IT",
            "falabella",
            37,
            38,
            "falabella",
            "IT",
            41,
            "falabella",
            43,
            44,
            "integraciones",
            46,
            47,
            "falabella",
            49,
            "IT",
            "falabella",
            52,
            53,
            "falabella",
            "IT",
            56,
            "falabella",
            58,
            59,
            "integraciones",
            61,
            62,
            "falabella",
            64,
            "IT",
            "falabella",
            67,
            68,
            "falabella",
            "IT",
            71,
            "falabella",
            73,
            74,
            "integraciones",
            76,
            77,
            "falabella",
            79,
            "IT",
            "falabella",
            82,
            83,
            "falabella",
            "IT",
            86,
            "falabella",
            88,
            89,
            "integraciones",
            91,
            92,
            "falabella",
            94,
            "IT",
            "falabella",
            97,
            98,
            "falabella",
            "IT",
        ], $this->counter->count1To100());
    }
}